### ISSUE TITLE
Exe build 2.2+ not working on XP

### ISSUE THREAD

**Issue by FrancoisSchnell** [unistra/avc-client#1]
When run on WinXP 32bits this build throw a  WindowsError: [Error 6] when supborcess attempts to launch and pipe with ffmpeg. 
It works from source code (from Eclipse) in XP but not when the build itself is launched (done with py2exe).
I tried many things like going with Shell=False to avoid platform specific shell issues and building on XP directly but to no avail. 
From now on build 2.2 and above will probably be targeted only at win7+ as XP is now soon out of maintenance and previous build are still available.

Unhandled exception in thread started by <function ffmpegAudioRecord at 0x03555630>
Traceback (most recent call last):
  File "mediacours.py", line 502, in ffmpegAudioRecord
  File "subprocess.pyc", line 701, in **init**
  File "subprocess.pyc", line 849, in _get_handles
  File "subprocess.pyc", line 883, in _make_inheritable
WindowsError: [Error 6] Descripteur non valide

**Comment by FrancoisSchnell** [comment]
won't support on XP anymore.
